### ISSUE TITLE
`did-insert` is not a helper

### ISSUE THREAD

**Issue by tlindsay** [FrontendMasters/ember-octane#4]
When we get to the ~4 hr mark, the course introduces Glimmer's lifecycle hooks. When I add them to my local copy, Glimmer starts throwing compile errors that `{{did-insert` and `{{did-update` aren't helpers.
 I've blown away `node_modules` and reinstalled.
```
$ ember -v
ember-cli: 3.11.0-beta.3
node: 10.16.0
os: darwin x64
```
```hbs
{{!-- chat-container.hbs --}}
<main class="flex-1 flex flex-col bg-white overflow-hidden channel">
  {{did-insert this.loadMessages}}
  {{yield this.messages}}
</main>
```
```js
// chat-container.js
import Component from '@glimmer/component';
import { tracked } from '@glimmer/tracking';
import { action } from '@ember/object';

export default class ChatContainerComponent extends Component {
  @tracked messages = [];

  @action async loadMessages() {
    const {
      channel: { id, teamId }
    } = this.args;

    const response = await fetch(`/api/teams/${teamId}/channels/${id}/messages`);
    this.messages = [
      ...this.messages,
      ...(await response.json())
    ];
  }
}
```
![image](https://user-images.githubusercontent.com/2797532/61332999-4e0ae200-a7eb-11e9-88ed-a89339cb6481.png)

**Comment by tlindsay** [comment]
I found the problem. I didn't realize that `did-insert` is a modifier, and I was calling it as a helper.
```
{{!-- BAD --}}
<main class="flex-1 flex flex-col bg-white overflow-hidden channel">
  {{did-insert this.loadMessages}}
  {{yield this.messages}}
</main>

{{!-- GOOD --}}
<main
  class="flex-1 flex flex-col bg-white overflow-hidden channel"
  {{did-insert this.loadMessages}}
  >
  {{yield this.messages}}
</main>
```

**Comment by elfin-sbreuers** [comment]
Thanks for finding that out. I am going through the pain of upgrading as well. That saved a lot of time.

**Comment by scriptmaster** [comment]
Also, with ember recent versions (I tested with 3.24) an additional install is required `ember install @ember/render-modifiers`

With @ember/render-modifiers installed, the error 'unexpected modifier did-insert' would be gone.

**Comment by Jackdawson007** [comment]
Install command
ember install @ember/render-modifiers

template.hbs
<p {{did-insert this.focusing}}>test</p>
<button {{on "click" this.handle}}>button</button>

template.js (controller)
import Controller from '@ember/controller';
import { action } from '@ember/object';
import { tracked } from '@glimmer/tracking';

export default class DashboardOverviewController extends Controller {
  @tracked myElement;

  @action
  focusing(element) {
    this.myElement = element;
  }

  @action
  handle() {
    this.myElement.innerText = "arunkumar";
  }
  
  Explanation :
  on the page onload you can take the element and store it on a tracked variable so after from that you can able to access that element where you want without using the document.getelementById and query selector or jquery without using these ok thank you 
 happy coding
  
  this was the best thing that was so useful for everyone right understand the code and if you have any doubt on it please fell free to ask me.
