### ISSUE TITLE
TeamSidebar doesn't span full height of the window

### ISSUE THREAD

**Issue by qpowell** [FrontendMasters/ember-octane#5]
After generating the component's JS module in the "Auth State and transitionTo" section, the  `TeamSidebar` component no longer spans the full height of the window.

I assume this is because of the wrapper div that gets added. Adding a `tagName = ' ';` to `app/components/team-sidebar.js` fixes it for me, or alternatively removing the outer section from the template and adding its classes to the component's `classNames`.

**Comment by mike-north** [comment]
Be sure you're using the Glimmer component base class. tagName and classNames only pertain to the old Ember.Component base class, which we never use in the octane course.

**Comment by qpowell** [comment]
@mike-north I was wondering why you didn't have to do that in the workshop. Looks like one of my VS code extensions autocompleted the import to the old one. Thanks!
